image: Visual Studio 2015
platform:
  - x64

install:
  ps: |
    Invoke-WebRequest 'http://download.qt.io/official_releases/jom/jom.zip' -OutFile .\jom.zip
    Expand-Archive .\jom.zip
    ls $(pwd)
    ls .\jom

