name: GammaRay Build

on: [push]

jobs:
  qt_build_test:
    runs-on: windows-2016
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install jom
        shell: powershell
        run: |
          Set-Location D:\
          Invoke-WebRequest 'http://download.qt.io/official_releases/jom/jom.zip' -OutFile .\jom.zip
          Expand-Archive .\jom.zip
          Remove-Item .\jom.zip
          Get-ChildItem $(pwd)
          Get-ChildItem .\jom
      - name: Clone Qt 5.6.3
        shell: cmd
        run: |
          cd D:\
          mkdir .\Qt\src\
          cd .\Qt\src\
          git clone -b v5.6.3 https://code.qt.io/qt/qt5.git 5.6.3
          cd .\5.6.3
          git submodule update --init --recursive
      - name: Clone latest GammaRay
        shell: cmd
        run: |
          cd D:\
          git clone https://github.com/KDAB/GammaRay.git
      - name: Build Qt 5.6.3 and GammaRay
        shell: cmd
        run: |
          dir
          .\build.bat
      - name: Copy Qt DLLs
        shell: powershell
        run: |
          $env:Path = "D:\Qt\build\5.6.3\qtbase\bin;" + $env:Path
          foreach ($_ in Get-ChildItem "D:\artifacts\bin" -Include *.exe,*.dll -Recurse) {
              & "D:\Qt\build\5.6.3\qtbase\bin\bin\windeployqt.exe" --release $_
          }
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: qt-GammaRay-x64-for-ida.zip
          path: D:\artifacts
